export const Users = [
  {
    id: 1,
    profilePicture: "profile/1.jpeg",
    userName: "Timo Elm",
  },
  { id: 2, profilePicture: "profile/2.jpg", userName: "Phoebe Buffy" },
  { id: 3, profilePicture: "profile/3.jpg", userName: "Ross Geller" },
  { id: 4, profilePicture: "profile/4.jpg", userName: "Rachel Green" },
  { id: 5, profilePicture: "profile/5.jpg", userName: "Chandler Bing" },
  { id: 6, profilePicture: "profile/6.jpg", userName: "Joey Tribbiani" },
  { id: 7, profilePicture: "profile/7.jpg", userName: "Monica Geller" },
];
export const Posts = [
  {
    id: 1,
    desc: "Everything in nature invites us constantly to be what we are.",
    photo: "post/pic-1.jpg",
    date: "5 min ago",
    userId: 1,
    like: 3,
    Comment: 5,
  },
  {
    id: 2,
    desc: "A life lived in love will never be dull...",
    photo: "post/pic-2.jpg",
    date: "12 min ago",
    userId: 2,
    like: 13,
    Comment: 7,
  },
  {
    id: 3,
    desc: "Life is a long lesson in humility",
    photo: "post/pic-3.jpg",
    date: "15 min ago",
    userId: 3,
    like: 9,
    Comment: 5,
  },
  {
    id: 4,
    desc: "Life is either a daring adventure or nothing at all.",
    photo: "post/pic-4.jpg",
    date: "20 min ago",
    userId: 4,
    like: 23,
    Comment: 5,
  },
  {
    id: 5,
    photo: "post/pic-5.jpg",
    date: "45 min ago",
    userId: 5,
    like: 3,
    Comment: 5,
  },
  {
    id: 6,
    desc: "Life is what happens when you're busy making other plans",
    photo: "post/pic-6.jpg",
    date: "1 Hour ago",
    userId: 6,
    like: 31,
    Comment: 5,
  },
  {
    id: 7,
    desc: "Whoever is happy will make others happy too",
    photo: "post/pic-7.jpg",
    date: "1 Hour ago",
    userId: 7,
    like: 3,
    Comment: 5,
  },
  {
    id: 8,
    desc: "The way to get started is to quit talking and begin doing",
    photo: "post/pic-8.jpg",
    date: "5 min ago",
    userId: 1,
    like: 3,
    Comment: 5,
  },
  {
    id: 9,
    desc: "Everything in nature invites us constantly to be what we are.",
    photo: "post/pic-9.jpg",
    date: "5 min ago",
    userId: 4,
    like: 3,
    Comment: 5,
  },
];
